---
- name: Enable container service
  ansible.builtin.systemd_service:
    name: "{{ container_name }}.service"
    daemon_reload: true
    state: restarted
    enabled: true
    scope: user
  become_user: "{{ service_user }}"
  become: true
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ user_info.uid }}"
